services:
  postgres:
    image: postgres:16-alpine
    container_name: world-cup-2026-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: world_cup_2026
    ports:
      - "5432:5432"
    volumes:
      - world_cup_2026_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: world-cup-2026-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - world_cup_2026_redis_data:/data
    command: redis-server --appendonly yes

volumes:
  world_cup_2026_postgres_data:
  world_cup_2026_redis_data: