services:
  api:
    build:
      context: .
      dockerfile: infra/docker/api.Dockerfile
    container_name: bolao-api
    env_file:
      - .env.local
    ports:
      - "${APP_PORT:-8080}:8080"
    networks:
      - bolao-network

  cronjob:
    build:
      context: .
      dockerfile: infra/docker/cronjob.Dockerfile
    container_name: bolao-cronjob
    env_file:
      - .env.local
    command: ["start-scheduler"]
    networks:
      - bolao-network

  frontend:
    build:
      context: .
      dockerfile: infra/docker/frontend.Dockerfile
    container_name: bolao-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      - api
    networks:
      - bolao-network

volumes:
  redis-data:

networks:
  bolao-network:
    driver: bridge