// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_tokens (
    user_id,
    token,
    expires_at
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, uuid, user_id, token, used, expires_at, created_at, used_at
`

type CreatePasswordResetTokenParams struct {
	UserID    int64
	Token     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.Token, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Token,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :exec
DELETE FROM password_reset_tokens
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPasswordResetTokens)
	return err
}

const getPasswordResetTokenByToken = `-- name: GetPasswordResetTokenByToken :one
SELECT id, uuid, user_id, token, used, expires_at, created_at, used_at
FROM password_reset_tokens
WHERE token = $1
LIMIT 1
`

func (q *Queries) GetPasswordResetTokenByToken(ctx context.Context, token string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByToken, token)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.UserID,
		&i.Token,
		&i.Used,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const invalidatePasswordResetTokensByUserID = `-- name: InvalidatePasswordResetTokensByUserID :exec
UPDATE password_reset_tokens
SET
    used = TRUE,
    used_at = NOW()
WHERE
    user_id = $1
    AND used = FALSE
`

func (q *Queries) InvalidatePasswordResetTokensByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, invalidatePasswordResetTokensByUserID, userID)
	return err
}

const listActivePasswordResetTokensByUserID = `-- name: ListActivePasswordResetTokensByUserID :many
SELECT id, uuid, user_id, token, used, expires_at, created_at, used_at
FROM password_reset_tokens
WHERE
    user_id = $1
    AND used = FALSE
    AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListActivePasswordResetTokensByUserID(ctx context.Context, userID int64) ([]PasswordResetToken, error) {
	rows, err := q.db.Query(ctx, listActivePasswordResetTokensByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PasswordResetToken
	for rows.Next() {
		var i PasswordResetToken
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.UserID,
			&i.Token,
			&i.Used,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const usePasswordResetToken = `-- name: UsePasswordResetToken :exec
UPDATE password_reset_tokens
SET
    used = TRUE,
    used_at = NOW()
WHERE id = $1
`

func (q *Queries) UsePasswordResetToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, usePasswordResetToken, id)
	return err
}
