// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: group.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (
    uuid, name, description, owner_id, invite_code
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, uuid, name, description, owner_id, invite_code, is_active, created_at, updated_at, deleted_at
`

type CreateGroupParams struct {
	Uuid        uuid.UUID
	Name        string
	Description pgtype.Text
	OwnerID     int64
	InviteCode  string
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Uuid,
		arg.Name,
		arg.Description,
		arg.OwnerID,
		arg.InviteCode,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.InviteCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createGroupMember = `-- name: CreateGroupMember :one
INSERT INTO group_members (
    uuid, group_id, user_id, role
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, uuid, group_id, user_id, role, joined_at, created_at, updated_at, deleted_at
`

type CreateGroupMemberParams struct {
	Uuid    uuid.UUID
	GroupID int64
	UserID  int64
	Role    string
}

func (q *Queries) CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, createGroupMember,
		arg.Uuid,
		arg.GroupID,
		arg.UserID,
		arg.Role,
	)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteGroupMember = `-- name: DeleteGroupMember :exec
UPDATE group_members
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE group_id = $1
AND user_id = $2
AND deleted_at IS NULL
`

type DeleteGroupMemberParams struct {
	GroupID int64
	UserID  int64
}

func (q *Queries) DeleteGroupMember(ctx context.Context, arg DeleteGroupMemberParams) error {
	_, err := q.db.Exec(ctx, deleteGroupMember, arg.GroupID, arg.UserID)
	return err
}

const getGroupByInviteCode = `-- name: GetGroupByInviteCode :one
SELECT id, uuid, name, description, owner_id, invite_code, is_active, created_at, updated_at, deleted_at FROM groups
WHERE invite_code = $1
AND deleted_at IS NULL
`

func (q *Queries) GetGroupByInviteCode(ctx context.Context, inviteCode string) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByInviteCode, inviteCode)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.InviteCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGroupByUUID = `-- name: GetGroupByUUID :one
SELECT id, uuid, name, description, owner_id, invite_code, is_active, created_at, updated_at, deleted_at FROM groups
WHERE uuid = $1
AND deleted_at IS NULL
`

func (q *Queries) GetGroupByUUID(ctx context.Context, argUuid uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroupByUUID, argUuid)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Description,
		&i.OwnerID,
		&i.InviteCode,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGroupMember = `-- name: GetGroupMember :one
SELECT id, uuid, group_id, user_id, role, joined_at, created_at, updated_at, deleted_at
FROM group_members
WHERE group_id = $1
AND user_id = $2
AND deleted_at IS NULL
`

type GetGroupMemberParams struct {
	GroupID int64
	UserID  int64
}

func (q *Queries) GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRow(ctx, getGroupMember, arg.GroupID, arg.UserID)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT id, uuid, group_id, user_id, role, joined_at, created_at, updated_at, deleted_at
FROM group_members
WHERE group_id = $1
AND deleted_at IS NULL
ORDER BY joined_at ASC
`

func (q *Queries) ListGroupMembers(ctx context.Context, groupID int64) ([]GroupMember, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupMember
	for rows.Next() {
		var i GroupMember
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupsByUserID = `-- name: ListGroupsByUserID :many
SELECT g.id, g.uuid, g.name, g.description, g.owner_id, g.invite_code, g.is_active, g.created_at, g.updated_at, g.deleted_at
FROM groups g
INNER JOIN group_members gm ON gm.group_id = g.id
WHERE gm.user_id = $1
AND g.deleted_at IS NULL
AND gm.deleted_at IS NULL
ORDER BY g.created_at DESC
`

func (q *Queries) ListGroupsByUserID(ctx context.Context, userID int64) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroupsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Description,
			&i.OwnerID,
			&i.InviteCode,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
