// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: job_control.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJobControl = `-- name: CreateJobControl :exec
INSERT INTO jobs_control (job)
VALUES ($1)
ON CONFLICT DO NOTHING
`

func (q *Queries) CreateJobControl(ctx context.Context, job string) error {
	_, err := q.db.Exec(ctx, createJobControl, job)
	return err
}

const getJobControl = `-- name: GetJobControl :one
SELECT job, last_success_run, is_enabled
FROM jobs_control
WHERE job = $1
`

type GetJobControlRow struct {
	Job            string
	LastSuccessRun pgtype.Timestamptz
	IsEnabled      bool
}

func (q *Queries) GetJobControl(ctx context.Context, job string) (GetJobControlRow, error) {
	row := q.db.QueryRow(ctx, getJobControl, job)
	var i GetJobControlRow
	err := row.Scan(&i.Job, &i.LastSuccessRun, &i.IsEnabled)
	return i, err
}

const updateJobControl = `-- name: UpdateJobControl :exec
UPDATE jobs_control
SET last_success_run = NOW(),
    updated_at = NOW()
WHERE job = $1
`

func (q *Queries) UpdateJobControl(ctx context.Context, job string) error {
	_, err := q.db.Exec(ctx, updateJobControl, job)
	return err
}
