// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: matches.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countMatches = `-- name: CountMatches :one
SELECT COUNT(*)
FROM matches m
WHERE m.deleted_at IS NULL
`

func (q *Queries) CountMatches(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMatches)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT m.id, m.uuid, m.external_id, m.stage, m.group_name, m.home_team_id, m.away_team_id, m.home_team_name, m.away_team_name, m.starts_at, m.home_score, m.away_score, m.status, m.winner_team_id, m.imported_at, m.created_at, m.updated_at, m.deleted_at, 
ht.flag_url AS home_team_flag_url, 
at.flag_url AS away_team_flag_url 
FROM 
matches m
LEFT JOIN teams ht ON ht.id = m.home_team_id
LEFT JOIN teams at ON at.id = m.away_team_id
WHERE m.id = $1
AND m.deleted_at IS NULL
`

type GetMatchByIDRow struct {
	ID              int64
	Uuid            uuid.UUID
	ExternalID      pgtype.Text
	Stage           string
	GroupName       pgtype.Text
	HomeTeamID      pgtype.Int8
	AwayTeamID      pgtype.Int8
	HomeTeamName    pgtype.Text
	AwayTeamName    pgtype.Text
	StartsAt        pgtype.Timestamptz
	HomeScore       pgtype.Int4
	AwayScore       pgtype.Int4
	Status          string
	WinnerTeamID    pgtype.Int8
	ImportedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	HomeTeamFlagUrl pgtype.Text
	AwayTeamFlagUrl pgtype.Text
}

func (q *Queries) GetMatchByID(ctx context.Context, id int64) (GetMatchByIDRow, error) {
	row := q.db.QueryRow(ctx, getMatchByID, id)
	var i GetMatchByIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ExternalID,
		&i.Stage,
		&i.GroupName,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomeTeamName,
		&i.AwayTeamName,
		&i.StartsAt,
		&i.HomeScore,
		&i.AwayScore,
		&i.Status,
		&i.WinnerTeamID,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HomeTeamFlagUrl,
		&i.AwayTeamFlagUrl,
	)
	return i, err
}

const getMatchByUUID = `-- name: GetMatchByUUID :one
SELECT m.id, m.uuid, m.external_id, m.stage, m.group_name, m.home_team_id, m.away_team_id, m.home_team_name, m.away_team_name, m.starts_at, m.home_score, m.away_score, m.status, m.winner_team_id, m.imported_at, m.created_at, m.updated_at, m.deleted_at, 
ht.flag_url AS home_team_flag_url, 
at.flag_url AS away_team_flag_url 
FROM 
matches m
LEFT JOIN teams ht ON ht.id = m.home_team_id
LEFT JOIN teams at ON at.id = m.away_team_id
WHERE m.uuid = $1
AND m.deleted_at IS NULL
`

type GetMatchByUUIDRow struct {
	ID              int64
	Uuid            uuid.UUID
	ExternalID      pgtype.Text
	Stage           string
	GroupName       pgtype.Text
	HomeTeamID      pgtype.Int8
	AwayTeamID      pgtype.Int8
	HomeTeamName    pgtype.Text
	AwayTeamName    pgtype.Text
	StartsAt        pgtype.Timestamptz
	HomeScore       pgtype.Int4
	AwayScore       pgtype.Int4
	Status          string
	WinnerTeamID    pgtype.Int8
	ImportedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	HomeTeamFlagUrl pgtype.Text
	AwayTeamFlagUrl pgtype.Text
}

func (q *Queries) GetMatchByUUID(ctx context.Context, argUuid uuid.UUID) (GetMatchByUUIDRow, error) {
	row := q.db.QueryRow(ctx, getMatchByUUID, argUuid)
	var i GetMatchByUUIDRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ExternalID,
		&i.Stage,
		&i.GroupName,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomeTeamName,
		&i.AwayTeamName,
		&i.StartsAt,
		&i.HomeScore,
		&i.AwayScore,
		&i.Status,
		&i.WinnerTeamID,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HomeTeamFlagUrl,
		&i.AwayTeamFlagUrl,
	)
	return i, err
}

const getNextMatch = `-- name: GetNextMatch :one
SELECT
    m.id, m.uuid, m.external_id, m.stage, m.group_name, m.home_team_id, m.away_team_id, m.home_team_name, m.away_team_name, m.starts_at, m.home_score, m.away_score, m.status, m.winner_team_id, m.imported_at, m.created_at, m.updated_at, m.deleted_at,
    ht.flag_url AS home_team_flag_url,
    at.flag_url AS away_team_flag_url
FROM matches m
LEFT JOIN teams ht ON ht.id = m.home_team_id
LEFT JOIN teams at ON at.id = m.away_team_id
WHERE m.deleted_at IS NULL
AND m.status = 'scheduled'
AND m.starts_at >= NOW()

ORDER BY m.starts_at ASC
LIMIT 1
`

type GetNextMatchRow struct {
	ID              int64
	Uuid            uuid.UUID
	ExternalID      pgtype.Text
	Stage           string
	GroupName       pgtype.Text
	HomeTeamID      pgtype.Int8
	AwayTeamID      pgtype.Int8
	HomeTeamName    pgtype.Text
	AwayTeamName    pgtype.Text
	StartsAt        pgtype.Timestamptz
	HomeScore       pgtype.Int4
	AwayScore       pgtype.Int4
	Status          string
	WinnerTeamID    pgtype.Int8
	ImportedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	HomeTeamFlagUrl pgtype.Text
	AwayTeamFlagUrl pgtype.Text
}

func (q *Queries) GetNextMatch(ctx context.Context) (GetNextMatchRow, error) {
	row := q.db.QueryRow(ctx, getNextMatch)
	var i GetNextMatchRow
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ExternalID,
		&i.Stage,
		&i.GroupName,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomeTeamName,
		&i.AwayTeamName,
		&i.StartsAt,
		&i.HomeScore,
		&i.AwayScore,
		&i.Status,
		&i.WinnerTeamID,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.HomeTeamFlagUrl,
		&i.AwayTeamFlagUrl,
	)
	return i, err
}

const listMatches = `-- name: ListMatches :many
SELECT
    m.id, m.uuid, m.external_id, m.stage, m.group_name, m.home_team_id, m.away_team_id, m.home_team_name, m.away_team_name, m.starts_at, m.home_score, m.away_score, m.status, m.winner_team_id, m.imported_at, m.created_at, m.updated_at, m.deleted_at,
    ht.flag_url AS home_team_flag_url,
    at.flag_url AS away_team_flag_url
FROM matches m
LEFT JOIN teams ht ON ht.id = m.home_team_id
LEFT JOIN teams at ON at.id = m.away_team_id
WHERE m.deleted_at IS NULL
ORDER BY m.starts_at ASC
`

type ListMatchesRow struct {
	ID              int64
	Uuid            uuid.UUID
	ExternalID      pgtype.Text
	Stage           string
	GroupName       pgtype.Text
	HomeTeamID      pgtype.Int8
	AwayTeamID      pgtype.Int8
	HomeTeamName    pgtype.Text
	AwayTeamName    pgtype.Text
	StartsAt        pgtype.Timestamptz
	HomeScore       pgtype.Int4
	AwayScore       pgtype.Int4
	Status          string
	WinnerTeamID    pgtype.Int8
	ImportedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
	HomeTeamFlagUrl pgtype.Text
	AwayTeamFlagUrl pgtype.Text
}

func (q *Queries) ListMatches(ctx context.Context) ([]ListMatchesRow, error) {
	rows, err := q.db.Query(ctx, listMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMatchesRow
	for rows.Next() {
		var i ListMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ExternalID,
			&i.Stage,
			&i.GroupName,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.HomeTeamName,
			&i.AwayTeamName,
			&i.StartsAt,
			&i.HomeScore,
			&i.AwayScore,
			&i.Status,
			&i.WinnerTeamID,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.HomeTeamFlagUrl,
			&i.AwayTeamFlagUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesByStage = `-- name: ListMatchesByStage :many
SELECT id, uuid, external_id, stage, group_name, home_team_id, away_team_id, home_team_name, away_team_name, starts_at, home_score, away_score, status, winner_team_id, imported_at, created_at, updated_at, deleted_at FROM matches
WHERE stage = $1
AND deleted_at IS NULL
ORDER BY starts_at ASC
`

func (q *Queries) ListMatchesByStage(ctx context.Context, stage string) ([]Match, error) {
	rows, err := q.db.Query(ctx, listMatchesByStage, stage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.ExternalID,
			&i.Stage,
			&i.GroupName,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.HomeTeamName,
			&i.AwayTeamName,
			&i.StartsAt,
			&i.HomeScore,
			&i.AwayScore,
			&i.Status,
			&i.WinnerTeamID,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMatch = `-- name: UpsertMatch :one
INSERT INTO matches (
    uuid,
    external_id,
    stage,
    group_name,
    home_team_id,
    away_team_id,
    home_team_name,
    away_team_name,
    starts_at,
    home_score,
    away_score,
    status,
    winner_team_id,
    imported_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, NOW()
)
ON CONFLICT (external_id)
DO UPDATE SET
    stage = EXCLUDED.stage,
    group_name = EXCLUDED.group_name,
    home_team_id = EXCLUDED.home_team_id,
    away_team_id = EXCLUDED.away_team_id,
    home_team_name = EXCLUDED.home_team_name,
    away_team_name = EXCLUDED.away_team_name,
    starts_at = EXCLUDED.starts_at,
    home_score = EXCLUDED.home_score,
    away_score = EXCLUDED.away_score,
    status = EXCLUDED.status,
    winner_team_id = EXCLUDED.winner_team_id,
    imported_at = NOW(),
    updated_at = NOW()
RETURNING id, uuid, external_id, stage, group_name, home_team_id, away_team_id, home_team_name, away_team_name, starts_at, home_score, away_score, status, winner_team_id, imported_at, created_at, updated_at, deleted_at
`

type UpsertMatchParams struct {
	Uuid         uuid.UUID
	ExternalID   pgtype.Text
	Stage        string
	GroupName    pgtype.Text
	HomeTeamID   pgtype.Int8
	AwayTeamID   pgtype.Int8
	HomeTeamName pgtype.Text
	AwayTeamName pgtype.Text
	StartsAt     pgtype.Timestamptz
	HomeScore    pgtype.Int4
	AwayScore    pgtype.Int4
	Status       string
	WinnerTeamID pgtype.Int8
}

func (q *Queries) UpsertMatch(ctx context.Context, arg UpsertMatchParams) (Match, error) {
	row := q.db.QueryRow(ctx, upsertMatch,
		arg.Uuid,
		arg.ExternalID,
		arg.Stage,
		arg.GroupName,
		arg.HomeTeamID,
		arg.AwayTeamID,
		arg.HomeTeamName,
		arg.AwayTeamName,
		arg.StartsAt,
		arg.HomeScore,
		arg.AwayScore,
		arg.Status,
		arg.WinnerTeamID,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ExternalID,
		&i.Stage,
		&i.GroupName,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.HomeTeamName,
		&i.AwayTeamName,
		&i.StartsAt,
		&i.HomeScore,
		&i.AwayScore,
		&i.Status,
		&i.WinnerTeamID,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
