// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Group struct {
	ID          int64
	Uuid        uuid.UUID
	Name        string
	Description pgtype.Text
	OwnerID     int64
	InviteCode  string
	IsActive    bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type GroupMember struct {
	ID        int64
	Uuid      uuid.UUID
	GroupID   int64
	UserID    int64
	Role      string
	JoinedAt  pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type JobsControl struct {
	Job            string
	LastSuccessRun pgtype.Timestamptz
	IsEnabled      bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Match struct {
	ID           int64
	Uuid         uuid.UUID
	ExternalID   pgtype.Text
	Stage        string
	GroupName    pgtype.Text
	HomeTeamID   pgtype.Int8
	AwayTeamID   pgtype.Int8
	HomeTeamName pgtype.Text
	AwayTeamName pgtype.Text
	StartsAt     pgtype.Timestamptz
	HomeScore    pgtype.Int4
	AwayScore    pgtype.Int4
	Status       string
	WinnerTeamID pgtype.Int8
	ImportedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type PasswordResetToken struct {
	ID        int64
	Uuid      uuid.UUID
	UserID    int64
	Token     string
	Used      bool
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}

type Prediction struct {
	ID           int64
	Uuid         uuid.UUID
	GroupID      int64
	UserID       int64
	MatchID      int64
	HomeScore    int32
	AwayScore    int32
	Points       float64
	Calculated   bool
	CalculatedAt pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type StageWeight struct {
	ID         int64
	Stage      string
	Weight     float64
	OrderIndex int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Team struct {
	ID         int64
	Uuid       uuid.UUID
	ExternalID pgtype.Text
	Name       string
	ShortName  pgtype.Text
	Code       pgtype.Text
	FlagUrl    pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type User struct {
	ID           int64
	Uuid         uuid.UUID
	Name         string
	Email        string
	PasswordHash string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}
