// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: ranking.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getGroupRanking = `-- name: GetGroupRanking :many
SELECT
    u.id AS user_id,
    u.uuid AS user_uuid,
    u.name,
    COALESCE(SUM(p.points), 0)::float8 AS total_points,
    COUNT(p.id) AS predictions_count
FROM group_members gm
INNER JOIN users u ON u.id = gm.user_id
LEFT JOIN predictions p 
    ON p.user_id = u.id 
    AND p.group_id = gm.group_id
    AND p.deleted_at IS NULL
WHERE gm.group_id = $1
AND gm.deleted_at IS NULL
AND u.deleted_at IS NULL
GROUP BY u.id, u.uuid, u.name
ORDER BY total_points DESC, u.name ASC
`

type GetGroupRankingRow struct {
	UserID           int64
	UserUuid         uuid.UUID
	Name             string
	TotalPoints      float64
	PredictionsCount int64
}

func (q *Queries) GetGroupRanking(ctx context.Context, groupID int64) ([]GetGroupRankingRow, error) {
	rows, err := q.db.Query(ctx, getGroupRanking, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupRankingRow
	for rows.Next() {
		var i GetGroupRankingRow
		if err := rows.Scan(
			&i.UserID,
			&i.UserUuid,
			&i.Name,
			&i.TotalPoints,
			&i.PredictionsCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupIDsByUserID = `-- name: ListGroupIDsByUserID :many
SELECT gm.group_id
FROM group_members gm
WHERE gm.user_id = $1
AND gm.deleted_at IS NULL
`

func (q *Queries) ListGroupIDsByUserID(ctx context.Context, userID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listGroupIDsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var group_id int64
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
