// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: stages.sql

package sqlc

import (
	"context"
)

const getStageWeight = `-- name: GetStageWeight :one
SELECT id, stage, weight, order_index, created_at, updated_at FROM stage_weights
WHERE stage = $1
`

func (q *Queries) GetStageWeight(ctx context.Context, stage string) (StageWeight, error) {
	row := q.db.QueryRow(ctx, getStageWeight, stage)
	var i StageWeight
	err := row.Scan(
		&i.ID,
		&i.Stage,
		&i.Weight,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStageWeights = `-- name: ListStageWeights :many
SELECT id, stage, weight, order_index, created_at, updated_at FROM stage_weights
ORDER BY order_index ASC
`

func (q *Queries) ListStageWeights(ctx context.Context) ([]StageWeight, error) {
	rows, err := q.db.Query(ctx, listStageWeights)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StageWeight
	for rows.Next() {
		var i StageWeight
		if err := rows.Scan(
			&i.ID,
			&i.Stage,
			&i.Weight,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
