// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: team.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const upsertTeam = `-- name: UpsertTeam :one
INSERT INTO teams (
    uuid,
    external_id,
    name,
    short_name,
    code,
    flag_url
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
ON CONFLICT (name)
DO UPDATE SET
    external_id = EXCLUDED.external_id,
    short_name = EXCLUDED.short_name,
    code = EXCLUDED.code,
    flag_url = EXCLUDED.flag_url,
    updated_at = NOW()
RETURNING id, uuid, external_id, name, short_name, code, flag_url, created_at, updated_at, deleted_at
`

type UpsertTeamParams struct {
	Uuid       uuid.UUID
	ExternalID pgtype.Text
	Name       string
	ShortName  pgtype.Text
	Code       pgtype.Text
	FlagUrl    pgtype.Text
}

func (q *Queries) UpsertTeam(ctx context.Context, arg UpsertTeamParams) (Team, error) {
	row := q.db.QueryRow(ctx, upsertTeam,
		arg.Uuid,
		arg.ExternalID,
		arg.Name,
		arg.ShortName,
		arg.Code,
		arg.FlagUrl,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.ExternalID,
		&i.Name,
		&i.ShortName,
		&i.Code,
		&i.FlagUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
